create table PROJECTS
(
ID number(*,0) primary key,
    CODE varchar2(255 byte) not null,
    MANAGER_ID number(*,0),
    BUDGET number(10,2) not null,
    DATE_OF_BEGINNING date,
    DATE_OF_ENDING date
    
);
ALTER TABLE PROJECTS
ADD CONSTRAINT FK_MANAGER_PROJECT
  FOREIGN KEY (MANAGER_ID)
  REFERENCES EMPLOYEES(id);
create table EMPLOYEES
(
    ID number(*,0) primary key,
    MANAGER_ID number(*,0),
    DATE_OF_JOINING date not null,
    FULL_NAME varchar2(255 byte) not null
);
ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_MANAGER_EMPLOYEE
  FOREIGN KEY (MANAGER_ID)
  REFERENCES EMPLOYEES(id);
ALTER TABLE PROJECTS
ADD CONSTRAINT FK_MANAGER_PROJECT
  FOREIGN KEY (MANAGER_ID)
  REFERENCES EMPLOYEES(id);
create table SALARIES
(
    ID number(*,0) primary key,
    EMPLOYEE_ID number(*,0) not null,
    PROJECT_ID number(*,0),
    SALARY number(10,2) not null
);
ALTER TABLE SALARIES
ADD CONSTRAINT FK_SALARY_EMPLOYEE
  FOREIGN KEY (EMPLOYEE_ID)
  REFERENCES EMPLOYEES(id);
  ALTER TABLE SALARIES
ADD CONSTRAINT FK_SALARY_PROJECT
  FOREIGN KEY (PROJECT_ID)
  REFERENCES EMPLOYEES(id);
